"""empty message

Revision ID: 275fa71ea0c3
Revises: 
Create Date: 2023-03-18 09:43:05.440205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275fa71ea0c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benutzerrolle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Administrator', sa.String(length=4), nullable=True),
    sa.Column('Trainer', sa.String(length=4), nullable=True),
    sa.Column('Benutzer', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maschine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('einstellung1', sa.String(length=10), nullable=True),
    sa.Column('einstellung2', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benutzername', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('passwort', sa.String(length=128), nullable=True),
    sa.Column('benutzerrolle', sa.Integer(), nullable=True),
    sa.Column('apitoken', sa.String(length=32), nullable=True),
    sa.Column('ablaufdatum', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['benutzerrolle'], ['benutzerrolle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benutzer_apitoken'), ['apitoken'], unique=True)
        batch_op.create_index(batch_op.f('ix_benutzer_benutzername'), ['benutzername'], unique=True)
        batch_op.create_index(batch_op.f('ix_benutzer_email'), ['email'], unique=True)

    op.create_table('trainingsplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benutzer', sa.Integer(), nullable=True),
    sa.Column('uebung', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['benutzer'], ['benutzer.id'], ),
    sa.ForeignKeyConstraint(['uebung'], ['maschine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainingsplan')
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benutzer_email'))
        batch_op.drop_index(batch_op.f('ix_benutzer_benutzername'))
        batch_op.drop_index(batch_op.f('ix_benutzer_apitoken'))

    op.drop_table('benutzer')
    op.drop_table('maschine')
    op.drop_table('benutzerrolle')
    # ### end Alembic commands ###
