"""empty message

Revision ID: cccb589b323a
Revises: 
Create Date: 2023-03-20 18:51:45.353421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccb589b323a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benutzername', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('passwort', sa.String(length=128), nullable=True),
    sa.Column('apitoken', sa.String(length=32), nullable=True),
    sa.Column('ablaufdatum', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benutzer_apitoken'), ['apitoken'], unique=True)
        batch_op.create_index(batch_op.f('ix_benutzer_benutzername'), ['benutzername'], unique=True)
        batch_op.create_index(batch_op.f('ix_benutzer_email'), ['email'], unique=True)

    op.create_table('maschine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('einstellung1', sa.String(length=10), nullable=True),
    sa.Column('einstellung2', sa.String(length=10), nullable=True),
    sa.Column('athlet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlet'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maschine')
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benutzer_email'))
        batch_op.drop_index(batch_op.f('ix_benutzer_benutzername'))
        batch_op.drop_index(batch_op.f('ix_benutzer_apitoken'))

    op.drop_table('benutzer')
    # ### end Alembic commands ###
